"""empty message

Revision ID: 91b9b6d84b92
Revises: 7657a9d48c5f
Create Date: 2021-07-28 16:47:47.784873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b9b6d84b92'
down_revision = '7657a9d48c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hired_trucks_id_no', table_name='hired_trucks')
    op.drop_table('hired_trucks')
    op.drop_table('trucks')
    op.add_column('user', sa.Column('name', sa.String(length=20), nullable=False))
    op.drop_column('user', 'uname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uname', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'name')
    op.create_table('trucks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('regno', sa.VARCHAR(length=100), nullable=False),
    sa.Column('truck_img', sa.VARCHAR(length=150), nullable=True),
    sa.Column('size', sa.VARCHAR(length=150), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hired_trucks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_no', sa.VARCHAR(length=8), nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_of_hire', sa.DATETIME(), nullable=True),
    sa.Column('truck_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_index('ix_hired_trucks_id_no', 'hired_trucks', ['id_no'], unique=False)
    # ### end Alembic commands ###
